#!/bin/bash
access/notPaid.py --nonPayers=outputs/notPaid --immunization
echo "-----------------------Non Payers --------------------------------------------"
cat outputs/notPaid.emails
echo "---------------------- Immunization ------------------------------------------"
cat outputs/Immunization.StudentInfo
