#!/bin/bash
access/studentInfo.py --List=$1 --Immunization --Graduates=2020 --Emails
# echo "-----------------------Sought --------------------------------------------"
# cat outputs/$1.emails
echo "---------------------- Immunization ------------------------------------------"
cat outputs/Immunization.StudentInfo
echo "---------------------- Graduates ---------------------------------------------"
cat outputs/Graduates.StudentInfo
echo "---------------------- Emails ---------------------------------------------"
echo "Split the Emails into groups small enough to send to"
cd outputs; split -a 1 -l 40 Emails Emails; cd ..
wc outputs/Emails*
# cat outputs/Emails.StudentInfo
